name: Publish Python to PyPI

on:
  push:
    branches:
      - main
    tags: 
      - v*
  workflow_dispatch:
    
jobs:
  build-publish:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install pypa/build
      run: >-
            python -m
            pip install
            build
            --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}